### ISSUE TITLE
Doesn't work in Firefox or Edge due to strict violation

### ISSUE THREAD

**Issue by nolanlawson** [fkling/astexplorer#140]
In both Firefox and Edge, the AST tree doesn't render due to a strict mode violation that Chrome is apparently lax about, but not Firefox or Edge.

![astexplorer](https://cloud.githubusercontent.com/assets/283842/17193920/1db5e542-540a-11e6-8378-25937563ba26.png)

The error in Edge (v14) is:

    SCRIPT1039: Octal numeric literals and escape characters not allowed in strict mode

The error in Firefox (v47.0.1) is:

    SyntaxError: octal literals and octal escape sequences are deprecated

The offending line of code seems to come from `babel-traverser`, although I admit I didn't dig too deep into the Webpack output. Perhaps some code that was not intended to be shipped as strict is getting enclosed in a strict mode context?

Here's a view of the offending line of code using Edge's F12 tools:

![astexplorer2](https://cloud.githubusercontent.com/assets/283842/17194016/991b055a-540a-11e6-9d0f-0e6d181539a0.png)

**Comment by hzoo** [comment]
hm from `babel-traverse`? might need more info

**Comment by RReverser** [comment]
Confirmed - not working in Edge; works in FF dev edition for me though.

**Comment by fkling** [comment]
This seems to have something to do with minification maybe, since this error doesn't appear when using `npm run watch`.

**Comment by fkling** [comment]
So, it seems the issue was with `flow_parser.js` and uglifyjs. `flow-parser.js` contains lots of strings on one line which seems to be processed by uglifyjs in such a way that an octal sequence is introduced? At least that's my conclusion since loading the parser works fine in watch mode (not minified). (cc @jeffmo).

I disabled minifying this file in e570b0fff8ba7a1650216970f62dbe7ec0276e38, so this shouldn't be an issue anymore. I'm able to load flow and jscodeshift in Firefox and Safari.
