### ISSUE TITLE
Use Monaco text editor

### ISSUE THREAD

**Issue by mohsen1** [fkling/astexplorer#196]
[Monaco](https://microsoft.github.io/monaco-editor/) with JavaScript and TypeScript services makes writing transformers easier by providing autocomplete. 

This will probably be a big change. I like to do it myself but want to make sure project owners agree with it.

**Comment by RReverser** [comment]
@mohsen1 Current editor provides autocomplete too, but obviously you need definitions :) But it certainly works, for example, for jscodeshift.

**Comment by thekip** [comment]
I  created the very basic implementation for jscodeshift editor with Monaco here
https://github.com/thekip/astexplorer/tree/typescript-support

I see for myself next benefits from that: 

- The autocomplete and code analysis is much much better than with CodeMirror and Tern. 
- Ability to use more popular community supported typings instead of Tern definitions.
- Ability to load typings "on-the-fly", for diffrent transforms (jscodeshift, tslint, eslint, etc)

Checklist

- [x] Basic integration + Webpack configuration for web workers
- [ ] `d.ts` Typings for JsCodeshift + Recast + AST Types [In Progress]
- [ ] Implement copying libraries typings during building, and loading in runtime for Monaco
- [ ] Polishing Webpack building configuartion
- [ ] Port all previous features / tight integration. Editor state saving/retrivieng, diffrent key mappings and etc.
- [ ] Integrate editor for code viewing, for source code, for output of transformation.
- [ ] Provide typings for rest transforms (tslint/eslint/etc)

**Comment by thekip** [comment]
Right now I'm stuck on how to expose module typings for global context in Monaco editor. 

I've created a question on [stack overflow](https://stackoverflow.com/questions/51538242/how-to-define-global-variable-in-monaco-editor-for-intellisense)

In question I mentioned typescript, but it actually applicable for all modern typings. 

The idea that you can type "typescript", hit ctrl+space, and see all typings without implicit import of library. (because it's not trivial to implement imports on frontend side)

**Comment by RReverser** [comment]
> because it's not trivial to implement imports on frontend side

Hmm, why not? It shouldn't be any harder than JS imports side which is already implemented. After all, you just have to `fetch` `.d.ts` in addition to regular JS and pass it to TypeScript via definitions option.

**Comment by thekip** [comment]
[RunKit](https://runkit.com/home) made a business on that. Implement true requires on frontend really hard, how you a going to require something that is not bundled yet?

**Comment by thekip** [comment]
Keeping in touch with progress. I rewrote typings generator for AST Types, and generated valid typings for Jscodeshift + AST Types and AST factories. 

I'm going to contribute to these projects separately (add typings directly to their repositories) or contribute typings to DefenetelyTyped. 

But meantime I will add what I already have to this branch, to unblock further work.

By the way, typings created by me very raw, and I probably need some help with refinement them.

**Comment by RReverser** [comment]
@thekip You can bundle them as static text alongside existing requires for JS (we use webpack which can do this quite easily).

**Comment by thekip** [comment]
@RReverser i don't understand what you talking about. Probably you didn't understand my issue. 
BTW it doesn't matter now, I got an answer from SO how to expose typings globally, and it works.

There was no problem with loading this typings to bundle. 

Anyway, I pushed last commits with new typings, and system to load this typings. 

It still very raw, I don't know how to associate parameters in transform function with Types without typescript annotations in the snippet.

**Comment by thekip** [comment]
@fkling i prepared it to the status when it satisfies my needs, and stopped development. 
You can pull my branch, and play with it. New Monaco editor implemented only for JsCodeshift transform and you need manually in the transform code associate variables with typings using JSdoc (I still didn't have a solution similar what have done in tern now, probably it even not possible).
```js
/**
 * this js doc is required to enable intellisense in Monaco
 * @param {FileObject} file
 * @param {ApiObject} api
 */
module.exports = function (file, api) {
...
}
```
Also I rewrote typings generator, to generate d.ts typings instead of tern's defs, and prepared way how to define and load definitions from transforms.

**Comment by thekip** [comment]
Update: And there are some building errors during development build, like: 

> ERROR in ./node_modules/prettier/index.js
Module parse failed: Invalid labeled declaration (4098:8)
You may need an appropriate loader to handle this file type.
|     }
|     _token_stack:
|         var lex = function () {
|             var token;
|             token = lexer.lex() || EOF;
 @ ./src/components/Editor.js 153:8-159:10
 @ ./src/containers/CodeEditorContainer.js
 @ ./src/app.js

I dind't fix them, you can just ignore it. Production build has much more errors, I did not get to them.
