### ISSUE TITLE
Can not import macros

### ISSUE THREAD

**Issue by danielo515** [fkling/astexplorer#372]
**Describe the bug**
Despite babel.macros is one of the built-in examples, you can not try them live on the site. When you try to import any macro you get a the following error:
```
Cannot read property 'charAt' of undefined
```

**To Reproduce**
1. Go to 'https://astexplorer.net'
2. Load the babel macro example by selecting transform babel-plugin-macros
3. Try to import the macro on the code to transpile `import pipe from "pipe.macro"`

**Expected behavior**
I expected the error not happening

**Screenshots**
here is an example gist:
https://astexplorer.net/#/gist/42b1bb055c2e9552a82cec24828fa451/2cafcfb9ffe716f782a4ab05532521975f9123bc

**Browser (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version latest

**astexplorer settings:**
- Selected parser: both babylon 7 and 6
- Selected transformer: babel-plugin-macros

**Comment by davidyu85** [comment]
I got similar issue, except I got the error message stated below:
i.statSync is not a function

danielo515's example gist shows the same error above for me.

**Comment by fkling** [comment]
`babel-plugin-macros` should work again, thanks to https://github.com/fkling/astexplorer/pull/381 . However, the example from Kent's website is still broken since it references the transformer by its old name. Maybe I can fix that, but it may be easier if @kentcdodds updates the URL to a working example.
