### ISSUE TITLE
Idea: make the parsers and transformers reusable for other purposes, like CLI / vscode extension

### ISSUE THREAD

**Issue by robert-j-webb** [fkling/astexplorer#417]
I love this project so much and there's really nothing like it. I found ast transforms to be the most enjoyable code to write in a large part due to the ease of how easy it is to visually see my code change in the website. 

However, I often run into a situation where I will write an ast transform and it will work on the astexplorer website, but I have no way to apply it to my code base, preventing me from doing a large scale edit. 

I recently attempted to fork the project and make it into a vscode extension  for the purpose of allowing directly editing and inspecting my code base directly. But I could not figure out how to get it to build. I don't really know enough about rollup to make the parsers and transforms reusable outside of the react frontend. 

Can anyone provide some guidance on how to do this? just an outline about what to do is enough. If possible, I'd love for this to be an upstream contribution rather than a fork. I understand that everyone is really busy with open source and I would do my best to do as much as possible to do the work on my own.

**Comment by rajasegar** [comment]
@robert-j-webb You need to take a look into [jscodeshift](https://github.com/facebook/jscodeshift). Because underlying all the transforms you are working in astexplorer, it is jscodeshift doing the majority of the work. Get yourself comfortable with the jscodeshift api, particularly the `transform` function.

Also regarding the parsers you can very well use them outside of astexplorer, since they are just compilers for different language semantics and syntax. A typical parser will have three api functions generally classified as:
- parse/process/preprocess => Read source code and convert into AST
- transform => This is where your jscodeshift comes into play which can manipulate the AST with its api
- print/generate => Convert modified AST back into source code.
I have written a blog [post](http://hangaroundtheweb.com/2019/03/codemods-the-new-age-saviors-for-js-developers/) regarding the same. [SHAMELESS SELF-PLUG]. Don't forget to check out the references at the end of the post.
Hope this helps!

**Comment by robert-j-webb** [comment]
Thanks I'll take a look at your blog post and jscodeshift and update this issue with my progress.

I think it would be awesome if the parsers/transformers were reusable!

**Comment by eventualbuddha** [comment]
@robert-j-webb you can also write your transforms as babel plugins and use [`@codemod/cli`](https://github.com/codemod-js/codemod/tree/master/packages/cli) to run them on your codebase. You can even directly pull code from an astexplorer.net URL:

```sh
$ codemod --remote-plugin URL …
```

**Comment by robert-j-webb** [comment]
Wow!!!!!!!!!!!!!!!!! Awesome
