### ISSUE TITLE
@typescript-eslint/parser cannot focus on right node

### ISSUE THREAD

**Issue by yatki** [fkling/astexplorer#431]
**Describe the bug**
I'm trying to create AST from TemplateLiterals. However, when I click on the text I cannot focus on the right nodes under expressions field. It highlights all quasis nodes instead.

**To Reproduce**
1. Go to 'https://astexplorer.net/'
2. Select 'Javascript'
3. Select '@typescript-eslint/parser'
4. Paste the snippet below on the left side:
```js
`This is ${example} ${example.two}`;
```
**Expected behavior**
When I click on `two`, I expect to navigate to MemberExpression node under `expressions`. However, It focuses to quasis field.
**Screenshots**
![image](https://user-images.githubusercontent.com/26697004/63215566-2207b700-c131-11e9-864d-0bff89a5dfcb.png)

**Browser (please complete the following information):**
 - Browser Chrome
 - Version 76.0.3809.100 (Official Build) (64-bit)

**astexplorer settings:**
- Selected parser: @typescript-eslint/parser

**Comment by fkling** [comment]
Interesting. I think this is why/how this happens:

- The location range of an array is the start index of its first element and the end index of its last element.
- A depth first approach is used to determine the node to highlight.

Since `quasis` is traversed before `expressions`, that's the one used.

---

Maybe the logic can be modified to do a more intelligent traversal, that would follow all  possible paths until the most specific one is found.

Having said that, I have some outstanding changes that already change how the focused node is computed, maybe this is already fixed there and if not I will see what I can do about it.

**Comment by yatki** [comment]
Looking forward to see the solution. Thanks for the great work so far 🖖🏻

**Comment by fkling** [comment]
So, it seems to work better with my changes, but it only because it highlights all leaf nodes within the range, i.e. the `quasis` array *and* the correct entry in the `expressions` array. Not sure if that is a feature or a bug :laughing: .

I will have to think about this.

However it is clear that the assumption is wrong that the location of an array is the start index of the first node and the end index of the last node. In the case of a template literal `quasis` and `expressions` are really just collections of individual nodes.

**Comment by fkling** [comment]
FWIW, I pushed the focus behavior changes. I think that highlighting both nodes as in the screenshot is actually a good thing. It's a bit confusing then which node to scroll to, but I'd argue that this is also not something that occurs too often.

Thanks again for reporting this. It made me reevaluate how I should treat arrays in the AST. Most arrays are not actual nodes in the AST, so for highlighting purposes I assigned them the starting position of the first node and the ending position of the last node. This works for most cases, but not here.

Now arrays are more "transparent". They are not considered for highlighting anymore.
