### ISSUE TITLE
Viewing an AST that includes a BigInt crashes because of JSON serialization

### ISSUE THREAD

**Issue by tmcw** [fkling/astexplorer#436]
**Describe the bug**

**To Reproduce**
1. Go to astexplorer.net
2. Change the parser to acorn and ecmaVersion to 11. Enter `0n` as the source
3. Click on the page
4. See error: BigInt could not be serialized, and the page becomes white

**Expected behavior**

BigInts are ignored or serialized as strings in JSON.

**Browser (please complete the following information):**
 - OS: macOS
 - Browser Chrome, Firefox

**astexplorer settings:**
- Selected parser: acorn
- Selected transformer (if applicable): none
- Contents of the local storage key `explorerSettingsV1` (code can be removed if you don't want it to be public)

```
{"showTransformPanel":false,"parserSettings":{"acorn":{"ecmaVersion":11,"sourceType":"module","allowReserved":false,"allowReturnOutsideFunction":false,"allowImportExportEverywhere":false,"allowAwaitOutsideFunction":false,"allowHashBang":false,"locations":false,"loose":false,"ranges":true,"preserveParens":false,"plugins.jsx":true},"remark":null,"typescript":null},"parserPerCategory":{"javascript":"acorn"},"workbench":{"parser":"acorn","code":"let x = 10n;","keyMap":"default","transform":{"code":"","transformer":null}}}
```

---

Thanks for astexplorer! I use it all the time, and it's super valuable for writing & debugging code for code.

**Comment by fkling** [comment]
Confirmed :+1:

**Comment by fkling** [comment]
I fixed that particular bug for the Tree view, but there is not much that can be done for the JSON view. However, I added error boundaries to the AST view, so that at least the site won't crash completely.

![Screen Shot 2019-09-06 at 23 58 05](https://user-images.githubusercontent.com/179026/64465714-77baf800-d10e-11e9-8657-c74de277c447.png)

**Comment by brettz9** [comment]
I'm seeing two problems as per the [screenshot](https://github.com/fkling/astexplorer/issues/436#issuecomment-529045135) that was shared. When choosing a parser (in my case `@typescript-eslint/parser`), and entering a bigint literal, and then clicking on the "JSON" view, I'm not clear why the app would need to break here. But even beyond that, the tree view then breaks and can only be fixed with a refresh.

**Comment by plasma4** [comment]
`BigInt.prototype.toJSON = function() { return this + "n" }` should do the trick.
