### ISSUE TITLE
Update @typescript-eslint/parser to support TypeScript 3.7 features

### ISSUE THREAD

**Issue by G-Rath** [fkling/astexplorer#451]
`@typescript-eslint/parser` is currently listed as being 1.13.0, but the latest version is 2.6.0.

In particular, use of optional chaining currently is marked as an error :(

TypeScript 3.7 is due for release tomorrow-ish (5th of Nov), which has official support for optional chaining & nullish coalescing.

**Comment by G-Rath** [comment]
@fkling I'm happy to help handle keeping the parsers up to date, as I use ASTExplorer quite a lot.

I'm assuming most of the time it's just a matter of doing what you did in 7ea2aea?

**Comment by fkling** [comment]
Help is certainly appreciated!
Eventually I would like to automate this as much as possible, but the biggest problem atm is build time. The other problem is that not every version upgrade can be done automatically.
So for now I'm trying to streamline the deployment process so that PR that update parser versions can be live as quickly as possible.

And yes, going into `website/` and running `yarn add package@latest` is often all that's necessary. If there are new parser options then those need to be added the the corresponding file as well.

**Comment by G-Rath** [comment]
> Eventually I would like to automate this as much as possible,

Keen for that!

> the biggest problem atm is build time.

Yeah, I'm having trouble even just building it in the first place - it keeps getting stuck on 89%.
Have you considered CDNing some of the packages?

That might not cut the build time in half, but it would be a pretty easy win vs the effort it would take.

> So for now I'm trying to streamline the deployment process so that PR that update parser versions can be live as quickly as possible.

Doubly keen for that!

> And yes, going into website/ and running yarn add package@latest is often all that's necessary.

Will do!

------

I've updated `yaml`, including adding the new options, but as I said my local build is stuck at 89% so I can't actually test it :(

**Comment by fkling** [comment]
> Have you considered CDNing some of the packages?
Yes. I could be wrong here since I didn't follow all the progress recently, but I believe this would only work if

- the package is already available as a single file (e.g. acorn)
- I'd use ES6 modules untranspiled and let the browser fetch dependencies as necessary from the CDN (e.g. babel is pretty big and spread over multiple modules)

My current goal is to actually completely separate the parser packages from the website and have them be built independently. That would probably make individual bundles slightly larger, but I think that's OK.
That also would enable other possibilities such as getting parsers from other sources than astexplorer itself.
I still have to hash out the details though. This does not mean no CDN sourcing though, this could still happen, but I think that the current architecture is fundamentally flawed.



>> So for now I'm trying to streamline the deployment process so that PR that update parser versions can be live as quickly as possible.

> Doubly keen for that!

I started playing around with GitLab CI/CD and it works pretty well so far. Anything merged into master will be deployed to https://staging.astexplorer.net automatically (the dev build though, since it's faster to build) and at the push of a button I can deploy it to the main site :)
Also people can see where a commit is deployed to.
I still have to figure some things out, especially if I want to move main development over to GitLab, but I will post more about this at some point.

> my local build is stuck at 89% so I can't actually test it :(

Use `yarn watch`. The development build is much faster (~ 3min). Then open `out/index.html`.

**Comment by fkling** [comment]
BTW, updates to both packages will be deployed soon, but I haven't added new options. If you get around to doing that, that would be awesome!

**Comment by NullVoxPopuli** [comment]
just tried @typescript-eslint/parser today, and it seems to be totally broken? (or there is a version mismatch?) 

It's reporting syntax errors on valid TS code (not sure what version)

example:
https://astexplorer.net/#/gist/17749b72484d8b00d6f159af4540eb9a/ee5b4b16962deb69bd90845db2d6d42896fda860

you'll also notice that the console.logs don't print at all

**Comment by fkling** [comment]
@NullVoxPopuli The error comes from eslint. Unfortunately the selected parser is in no way connected to the selected transformer. I know that that's confusing and annoying and I'm working towards a solution for it.
