### ISSUE TITLE
often freezes when using htmlparser2

### ISSUE THREAD

**Issue by jedwards1211** [fkling/astexplorer#501]
**Describe the bug**
Not sure if there's a bug in htmlparser2 or AST explorer, but it often freezes when I try to change the source HTML when htmlparser2 is selected.

**To Reproduce**
1. Change source type to HTML to get default example
2. Change parser to htmlparser2
3. Add some whitespace to the source

It usually freezes on step 2 or 3.

**Expected behavior**
continues to respond

**Browser (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 81.0.4044.129

**Comment by fkling** [comment]
I can reproduce this by selecting in the parser and just clicking around the source code (Firefox, Linux).

It's an interesting case. On one hand I don't see this issue with other parsers, so that seems to suggest that there is an issue with htmlparser2 itself.
But on the other hand, the parser isn't involved anymore when clicking around the source code and highlighting AST nodes. So maybe the issue is with the AST itself.

**Comment by fkling** [comment]
Looks like the problem is that `parentNode` points back to parent, causing the focus logic to be stuck in a loop?
Autofocus in general doesn't seem to work that great due to the `previousSibling` and `nextSibling` properties.
I guess for the purpose of this tool it's OK to ignore those? I should something that still shows the properties in the tree view but omits their value and instead shows an explanation for why they have been removed.

**Comment by jedwards1211** [comment]
Ah, yeah I agree it's fine to remove those properties.
