### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by marcandre** [fkling/astexplorer#536]
I really like the functionality of AST explorer and would like to use something similar to display [RuboCop's NodePattern](https://docs.rubocop.org/rubocop-ast/node_pattern.html) (with additional matching info like rubular.com).

I haven't looked deeply into it, but it looks like the nice AST viewer is custom and not an external package, right? If so, what is the license?

**Comment by fkling** [comment]
Hi @marcandre!

I originally didn't look into licenses because I actually didn't want people to create one-off astexplorer clones for a single parser. I'm not sure if it still makes sense to hold onto  that.

But regardless of that, I could definitely how just the "tree view" could be a standalone package. I actually started a rewrite of astexplorer that might make it easier to bundle the view separately. I would have think a bit more about its interface so that it doesn't depend on other parts of the astexplorer site.

Do you already have an idea of how you'd want to integrate it if it existed standalone? How would your ideal API look like?

**Comment by marcandre** [comment]
TBH, the tree view might be a bit of an overkill for my needs, but if it was available it could be nice to use it. 

I just put up a proof of concept of my tool, http://nodepattern.herokuapp.com/
There's zero help right now so it's hard to understand, but the Ruby code one inputs in the bottom left corner shows up in AST form in the top right corner. The main focus of my tool is to check if the [NodePattern](https://docs.rubocop.org/rubocop-ast/node_pattern.html) (think regexp but for AST, top left) matches the Ruby AST; if so, captures show in the bottom right.

In terms of API, your needs are much bigger than mine, so anything that works for you should work for me. In particular, making it easy to highlight text in a CodeMirror to the TreeView and vice versa would be cool (I already output [unist](https://github.com/syntax-tree/unist)).

**Comment by fkling** [comment]
I added the MIT license in the meantime.
