### ISSUE TITLE
Need for migration due to Parse shutdown?

### ISSUE THREAD

**Issue by RReverser** [fkling/astexplorer#94]
Apparently Facebook shuts down Parse.com http://bits.blogs.nytimes.com/2016/01/28/facebook-to-shut-down-parse-its-platform-for-mobile-developers/. IIUC, this affects us, and even though there is plenty of time for migration, decided to bring this up to attention rather sooner.

**Comment by fkling** [comment]
Yes, I'm open for suggestions. One solution could be to host https://github.com/ParsePlatform/parse-server on e.g. Digital Ocean. Having our own server may allow us to do other great things we haven't thought about yet.

But finding something that doesn't cost anything would be great too ;)

**Comment by RReverser** [comment]
> But finding something that doesn't cost anything would be great too ;)

Well, one way could be encoding the inputs in the URL itself like Babel REPL does, but it has some serious limitations on the size. We could experiment with gzipping, but not sure whether it will help much.

**Comment by RReverser** [comment]
How about Firebase free plan? Will it be sufficient for our needs? https://www.firebase.com/pricing.html

**Comment by alyssoncm** [comment]
I'm a web and mobile developer. Parse it is a good solution for a quick app backend setup but I never realized build big things over there. To me the most important to me is no vendor lock-in I see as very important to have full control over what I'm developing. I started to use a great platform http://parse.back4app.com (http://parse.back4apps.com) and I'm happy with the results. I recommend it as a migration option. At any moment you can have your code totally portable.  It is easy-to-use (MDD oriented) and they have a migration plan for parse.

**Comment by Daniel15** [comment]
I think the easiest thing will be to run your own Parse server (https://github.com/ParsePlatform/parse-server) as in theory that means all the client-side code can remain the same.

> But finding something that doesn't cost anything would be great too ;)

You could find someone that's willing to sponsor it. Depends on resource consumption. Do you know how much disk space / bandwidth the site currently uses?

**Comment by fkling** [comment]
Small update: 
- Parse has a good [generic migration guide](https://parse.com/migration).
- I'm looking into [DigitalOcean](https://www.digitalocean.com/) + [Docker](https://www.docker.com/). 

The smallest server is $5/mo which I'm willing to pay. The advantage of running our own server is that we could also run an additional service to parse languages for which no parser implementation in JS exist. We can also use GH's webhooks to automatically deploy new versions of astexplorer.

I already got MongoDB + parse server + http server running locally, but it will still take a while since I want to make myself more familiar with Docker first. I thought investing in Docker could be useful since it appears it makes it easier for us to move somewhere else if needed.

I would like to create a new GH repo for the server if I figure out how to handle the sensitive information (maybe [git-cipher](https://github.com/wincent/git-cipher)).

**Comment by Daniel15** [comment]
DigitalOcean are okay, but consider Linode and BuyVM too. Personally I'm very happy with BuyVM, but Linode are currently better value than DigitalOcean in case you need more RAM ($10/month at Linode gets you 2 GB RAM, compared to only 1 GB RAM at DigitalOcean). 512 MB can be a bit tight if you want to run several services on the box (particularly if you want to host a database server on the box). I'd suggest looking at 1 GB RAM at least.

You could take a look at https://lowendbox.com/ too, which lists cheap VPS deals. In the end it doesn't really matter too much, VPS hosts are pretty much all the same :stuck_out_tongue: . You could even get a few VPSes and benchmark them / their network. That's what I did when I was choosing a host, and how I ended up picking BuyVM.

At some point you could totally throw away Parse and just have your own CRUD endpoints (could be small PHP scripts for example), which would let you choose exactly which technologies you'd like to use, rather than having to stick with Parse. Up to you! :smile: 

> I would like to create a new GH repo for the server if I figure out how to handle the sensitive information 

Personally I feel uneasy having secrets checked in to Git, even if they're encrypted. What I do is have a config file that's excluded from Git, and then just manually edit that file on the server. Not sure how well that'd play with Docker, though (I don't use Docker for any of my personal sites, so I don't have experience with it).

**Comment by fkling** [comment]
Thanks for all the suggestions @Daniel15!

**Comment by fkling** [comment]
After looking more into DigitalOcean, Linode and my webhoster in Germany (https://www.df.eu if you are curious), I think I will go with Linode. They offer 2GB memory and daily backups for a reasonable price.

I have set up a private GH repository with the server code. Docker makes this quite easy actually. I plan to open source it after the data migration is complete.
If somebody wants to take a look at the repo or help out, let me know.

Also in general, if somebody wants commit access and help keep astexplorer up to date let me know too :)

---

Even though I'm quite content with running our own server now, does anybody have any other ideas how we could run astexplorer and preserve the existing data?

**Comment by TimothyGu** [comment]
We could host the static resources of the website on S3/Cloudfront and use Amazon API Gateway hooked onto one of the Amazon DB services. Not the most convenient to set up, and probably takes a bit of time to transfer the data over, but then the service is fully managed and scalable.

Just an idea.

**Comment by Daniel15** [comment]
> does anybody have any other ideas how we could run astexplorer and preserve the existing data?

Export it from the existing backend, import it into the new one? I assume Parse allows you to export the data - It *is* your data, after all.

> but then the service will be fully managed and scalable. 

How scalable does something like ASTExplorer need to be though?  Most of the work is done client-side. All the server side is doing is basically just storing a blob of text, right? Even a the worst shared hosting (like a Hostgator or GoDaddy account) would be able to handle that :stuck_out_tongue:

**Comment by fkling** [comment]
@TimothyGu: Is there something that AWS doesn't have o_O . This is interesting, I will look a bit more into it. It looks like it could be (relatively) easy to migrate to DynamoDB. Scalability is not my main concern right now, but using a managed service (like this one) would be fantastic. It will probably be cheaper too (I guess even free since we probably don't need more than what amazon's free tier provides).
The website is currently hosted on GitHub actually and it could easily stay there.

@Daniel15: 
> Export it from the existing backend, import it into the new one?

Lol, I get that ;) I was looking for something more concrete :D Anyways, @TimothyGu suggestion looks good. I agree that scaleability is not really a concern, but the fact that Amazon's DB services are managed is a huge benefit. I don't want to run my own server if I don't have to :)

**Comment by Daniel15** [comment]
> I guess even free since we probably don't need more than what amazon's free tier provides

Free tier is only free for one year, after which it'll probably end up costing more than hosting it yourself (as generally SaaS costs more than IaaS). It might be a worthwhile option though! Definitely worth investigating :smile:

**Comment by fkling** [comment]
> Free tier is only free for one year

Some services seem to stay free, including DynamoDB! 😄 25GB storage + 20 read and write capacity units seems to be plenty for astexplorer.

> These free tier offers do not automatically expire at the end of your 12 month AWS Free Tier term and are available to all AWS customers.
https://aws.amazon.com/free/

---

> It might be a worthwhile option though! Definitely worth investigating 😄

Yep. It also depends on how easily it would be to convert to the other DB and how to integrate with it.

**Comment by fkling** [comment]
After looking at DynamoDB it seems that it would require some effort to format and import the data to it.

In the short term, I might just go ahead with a custom server and in the long term we can look for alternative storage solutions (e.g. move everything over to gists 😉 )

**Comment by TimothyGu** [comment]
> (e.g. move everything over to gists :wink:)

Indeed this is something I've thought of for my project as well. But the thing about Gists is that you either authenticate, or you don't. If you authenticate the user with GitHub, then you'll have to use a server of some sort. If you don't, the revision feature won't work.

So yeah, the dedicated server is probably the best option in the mean time.

**Comment by pivanov** [comment]
You should check www.sashido.io :)

**Comment by fkling** [comment]
See #184 for current information about this issue.
